### ISSUE TITLE
automate the sharing-model and user-profile to facilitate service execution

### ISSUE THREAD

**Issue by cjdcordeiro** [mF2C/LifecycleManagement#18]
The idea is to:

 - [ ] remove the `user` reference/dependency from the service launch (@fcarp10 and @rsucasas)
 - [ ] (@alxjand ) add two checkboxes and 1 html counter to the Download GUI page, that should be passed dynamically into the compose file (same thing as for IDKey). These values must go into the `lm-um` service, as env variables (SERVICE_CONSUMER, RESOURCE_CONTRIBUTOR, MAX_APPS), so it should look like this:

```
  lm-um:
    image: mf2c/lifecycle-usermngt:1.0.6b
    restart: on-failure
    expose:
      - "46300"
      - "46000"
    ports:
      - "46000:46000"
      - "46300:46300"
    environment:
      - DOCKER_SWARM=True
      - K8S_MASTER=False
      - HOST_IP=192.168.252.41
      - DATACLAY_EP=
      - WORKING_DIR_VOLUME=/tmp/compose_files
      - SERVICE_CONSUMER=true/false
      - RESOURCE_CONTRIBUTOR=true/false
      - MAX_APPS=#
    volumes:
      - /tmp/compose_files:/tmp/compose_files
      - /var/run/docker.sock:/var/run/docker.sock
```

 - [ ] if these env vars are not in the compose file, then we take default values so we can automatically create the user-profile and sharing-model (@rsucasas )
